Referee
illini-robomaster/iRM_Embedded_2022 pull request #17
Opened 2022-01-12 03:27 UTC by AlchemicRonin

2022-01-13 00:11 UTC, Fred-Hou requested changes

2022-01-13 00:11 UTC, Fred-Hou commented on examples/referee/main.cc
> +//      print("\r\n");
Please consider deleting unused code...

2022-01-13 00:11 UTC, Fred-Hou commented on shared/libraries/referee.cc
> +        for (; ++end_idx < length && buffer[end_idx] != SOF;);
Please consider using another statement.

2022-01-14 00:42 UTC, AlchemicRonin commented on examples/referee/main.cc
> +//      print("\r\n");
```suggestion
```

2022-01-14 01:07 UTC, merged